name: 'brownrice_dbt'
version: '1.0.0'
config-version: 2

profile: 'brownrice_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  brownrice_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
